# Generated by Django 5.1.1 on 2025-01-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='game',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start_time',
        ),
    ]
