# Generated by Django 5.1.1 on 2025-01-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_game_admin_remove_game_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
