# Generated by Django 5.1.1 on 2025-01-12 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='address',
            field=models.CharField(default='ig11 9bx', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='postcode',
            field=models.CharField(default='ig11 9bs', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='totalPlayers',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('team', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='api.Player', to=settings.AUTH_USER_MODEL),
        ),
    ]
