# Generated by Django 5.1.1 on 2025-01-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_game_address_game_name_game_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
