# Generated by Django 5.1.1 on 2025-01-13 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_game_end_time_alter_game_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 13)),
            preserve_default=False,
        ),
    ]
