# Generated by Django 5.1.1 on 2025-01-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fulltime',
            field=models.BooleanField(default=False),
        ),
    ]
