# Generated by Django 5.1.1 on 2025-01-20 16:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_game_fulltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=(0.105618, 51.549457), srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='postcode',
            field=models.CharField(default='IG11 9BX', max_length=50),
            preserve_default=False,
        ),
    ]
